version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dias
      POSTGRES_USER: dias
      POSTGRES_DB: dias
    restart: always